const OPERATIONAL_LOG_TYPE = 'OPERATIONAL_LOG_TYPE';
const BUSINESS_LOG_TYPE = 'BUSINESS_LOG_TYPE';
const INFO_SEVERITY = 'INFO';
const ERROR_SEVERITY = 'ERROR';
const BUY_ACTION = 'BUY';
const SELL_ACTION = 'SELL';

module.exports = {
  OPERATIONAL_LOG_TYPE, BUSINESS_LOG_TYPE, INFO_SEVERITY, ERROR_SEVERITY, BUY_ACTION, SELL_ACTION,
};
